# Generated by Django 5.2.17 on 2026-10-03 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_asset_library'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PagePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=1000)),
                ('principal_type', models.CharField(choices=[('user', 'user'), ('group', 'group')], max_length=5)),
                ('action', models.CharField(choices=[('view', 'view'), ('edit', 'edit')], max_length=4)),
                ('effect', models.CharField(choices=[('allow', 'allow'), ('deny', 'deny')], max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_permissions', to='auth.group')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('principal_type', 'user')), fields=('path', 'user', 'action'), name='pageperm_user_unique'), models.UniqueConstraint(condition=models.Q(('principal_type', 'group')), fields=('path', 'group', 'action'), name='pageperm_group_unique')],
            },
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('body', models.TextField(blank=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_revisions', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='api.page')),
            ],
            options={
                'ordering': ['-number'],
                'indexes': [models.Index(fields=['page', 'number'], name='api_revisio_page_id_b2e0cc_idx')],
                'constraints': [models.UniqueConstraint(fields=('page', 'number'), name='revision_page_number_unique')],
            },
        ),
    ]
